### ISSUE TITLE
Choose constructor?

### ISSUE THREAD

**Issue by Altreus** [lizmat/ObjectCache#2]
In line with my REST use case from #1, I wonder if I could wrap `fetch` instead of `new`, essentially memoizing a factory method?

I don't mind refactoring to use `new` to construct the objects, and do a fetch from the constructor, but that seems like I would be overloading my constructor in a way I'm not sure I like.

**Comment by lizmat** [comment]
You can use *any* method to create objects, as long as they call `.bless` internally.  The "magic" of `ObjectCache` is not in intercepting `new`, but the "hidden" `bless` method.

    method fetch($foo) { self.bless(:$foo) }

should just work  :-)
